---
- name: Run SQL Command on DB
  hosts: all
  tasks:
  - name: Execute run sql command on DB Script
    script: run_sql_command.ps1 -instanceName {{ mssql.instance_name }} -dbName {{ mssql.db_name }} -sqlQuery "{{ mssql.sql_query }}"


