---
- name: Restore DB from latest Backup
  hosts: all
  tasks:
  - name: Run restore db from latest backup script
    script: restore_latest_db.ps1 -instanceName {{ instance_name }} -dbName {{ db_name }} 

