---
- name: Run SQL Command in Instance
  hosts: all
  tasks:
  - name: Execute run sql command on instance script
    script: run_sql_command.ps1 -instanceName {{ instance_name }} -sqlQuery "{{ sql_query }}"

