---
- hosts: all

  tasks:
    - name: create db
      mssql_db:
        login_host: {{ mssql.login_host }}
        login_user: {{ mssql.login_user }}
        login_password: {{ mssql.login_password }}
        login_port: {{ mssql.login_port }}
        name: redhatdemo
        state: present