---
- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Remove instances
    os_server:
         state: absent
         auth:
           auth_url: http://192.168.2.2:5000/v2.0
           username: admin
           password: r3dh4t!
           project_name: admin
         name: "{{ item }}"
         image: rhel73
         key_name: default
         timeout: 200
         flavor: 2
         auto_ip: yes
         nics:
           - net-name: private_network
         meta:
           hostname: "{{ item }}.home.ad"
           group: rolling_app
    register: newnode
    with_items:
      - web1
      - web2
      - db1
      - lb1

