---

- name: text expect
  hosts: all

  tasks:

    - debug: msg="{{ hostvars }}"

    - name: run test file
      expect:
        command: ssh -i /var/lib/awx/openstack-default.pem {{ ansible_ssh_user }}@{{ ansible_ssh_host }} /home/cloud-user/test_expect.sh
        responses:
          'your choice': 'abcd'
      delegate_to: 127.0.0.1
