---
- name: text expect
  hosts: all

  tasks:

    - name: copy test_expect.sh file
      copy: src=test_expect.sh dest=/home/cloud-user/ mode=0744

    - name: run test file
      expect:
        command: ssh cloud-user@{{ ansible_ssh_host }} /home/cloud-user/test_expect.sh
        responses:
          'your choice': 'abcd113'
      delegate_to: 127.0.0.1
